import settings

namespaces = [
  {'namespace': 'article'},
  {'namespace': 'person'},
  {'namespace': 'ref'},
  {'namespace': 'alm'},
]

tags = [
  {'tag': 'article/doi',		'desc': ''},
  {'tag': 'article/doi-url',		'desc': ''},
  {'tag': 'article/pmid',		'desc': ''},
  {'tag': 'article/journal-id',		'desc': ''},
  {'tag': 'article/journal-title',		'desc': ''},
  {'tag': 'article/journal-issn-ppub',		'desc': ''},
  {'tag': 'article/journal-issn-epub',		'desc': ''},
  {'tag': 'article/publisher',		'desc': ''},
  {'tag': 'article/article-title',		'desc': ''},
  {'tag': 'article/abstract',		'desc': ''},
  {'tag': 'article/article-type',		'desc': ''},
  {'tag': 'article/article-institution',		'desc': ''},
  {'tag': 'article/article-country',		'desc': ''},
  {'tag': 'article/subject-area',		'desc': ''},
  {'tag': 'article/research-organism',		'desc': ''},
  {'tag': 'article/author',		'desc': ''},
  {'tag': 'article/author-surname',		'desc': ''},
  {'tag': 'article/author-given-names',		'desc': ''},
  {'tag': 'article/author-department',		'desc': ''},
  {'tag': 'article/author-institution',		'desc': ''},
  {'tag': 'article/author-city',		'desc': ''},
  {'tag': 'article/author-country',		'desc': ''},
  {'tag': 'article/author-corresponding',		'desc': ''},
  {'tag': 'article/author-corresponding-surname',		'desc': ''},
  {'tag': 'article/author-corresponding-given-names',		'desc': ''},
  {'tag': 'article/author-corresponding-department',		'desc': ''},
  {'tag': 'article/author-corresponding-institution',		'desc': ''},
  {'tag': 'article/author-corresponding-city',		'desc': ''},
  {'tag': 'article/author-corresponding-country',		'desc': ''},
  {'tag': 'article/correspondence',		'desc': ''},
  {'tag': 'article/author-notes',		'desc': ''},
  {'tag': 'article/keyword',		'desc': ''},
  {'tag': 'article/pub-date-date',		'desc': ''},
  {'tag': 'article/pub-date-day',		'desc': ''},
  {'tag': 'article/pub-date-month',		'desc': ''},
  {'tag': 'article/pub-date-year',		'desc': ''},
  {'tag': 'article/pub-date-timestamp',		'desc': ''},
  {'tag': 'article/received-date-date',		'desc': ''},
  {'tag': 'article/received-date-day',		'desc': ''},
  {'tag': 'article/received-date-month',		'desc': ''},
  {'tag': 'article/received-date-year',		'desc': ''},
  {'tag': 'article/received-date-timestamp',		'desc': ''},
  {'tag': 'article/accepted-date-date',		'desc': ''},
  {'tag': 'article/accepted-date-day',		'desc': ''},
  {'tag': 'article/accepted-date-month',		'desc': ''},
  {'tag': 'article/accepted-date-year',		'desc': ''},
  {'tag': 'article/accepted-date-timestamp',		'desc': ''},
  {'tag': 'article/award-group-funding-source',		'desc': ''},
  {'tag': 'article/award-group-award-id',		'desc': ''},
  {'tag': 'article/award-group-principle-award-recipient',		'desc': ''},
  {'tag': 'article/funding-statement',		'desc': ''},
  {'tag': 'article/copyright-statement',		'desc': ''},
  {'tag': 'article/copyright-year',		'desc': ''},
  {'tag': 'article/copyright-holder',		'desc': ''},
  {'tag': 'article/license',		'desc': ''},
  {'tag': 'article/license-type',		'desc': ''},
  {'tag': 'article/license-url',		'desc': ''},
  {'tag': 'article/ack',		'desc': ''},
  {'tag': 'article/conflict',		'desc': ''},
  {'tag': 'article/ref',		'desc': ''},
  {'tag': 'article/ref-publication-type',		'desc': ''},
  {'tag': 'article/ref-article-title',		'desc': ''},
  {'tag': 'article/ref-authors',		'desc': ''},
  {'tag': 'article/ref-year',		'desc': ''},
  {'tag': 'article/ref-source',		'desc': ''},
  {'tag': 'article/ref-volume',		'desc': ''},
  {'tag': 'article/ref-fpage',		'desc': ''},
  {'tag': 'article/ref-lpage',		'desc': ''},
  {'tag': 'article/ref-doi',		'desc': ''},
  {'tag': 'article/ref-pmid',		'desc': ''},
  {'tag': 'article/ref-collab',		'desc': ''},
  {'tag': 'article/ref-publisher-loc',		'desc': ''},
  {'tag': 'article/ref-publisher-name',		'desc': ''},
  {'tag': 'article/citation',		'desc': ''},
  
  {'tag': 'person/surname',		'desc': ''},
  
  {'tag': 'ref/article-title',		'desc': ''},
  {'tag': 'ref/publication-type',		'desc': ''},
  {'tag': 'ref/doi',		'desc': ''},
  {'tag': 'ref/pmid',		'desc': ''},
  {'tag': 'ref/author',		'desc': ''},
  {'tag': 'ref/year',		'desc': ''},
  {'tag': 'ref/source',		'desc': ''},
  {'tag': 'ref/volume',		'desc': ''},
  {'tag': 'ref/fpage',		'desc': ''},
  {'tag': 'ref/lpage',		'desc': ''},

  {'tag': 'alm/doi',		'desc': ''},
  {'tag': 'alm/source',		'desc': ''},
  {'tag': 'alm/value',		'desc': ''},
  {'tag': 'alm/timespan',		'desc': ''},
  {'tag': 'alm/date-date',		'desc': ''},
  {'tag': 'alm/date-day',		'desc': ''},
  {'tag': 'alm/date-month',		'desc': ''},
  {'tag': 'alm/date-year',		'desc': ''},
  {'tag': 'alm/date-timestamp',		'desc': ''},
  
]

objects = [
    {'obj': 'df97444e-9579-49f1-8302-2dce51c0bd95', 'doi': '10.7554/eLife.000536', 'query':
      {'queries':
        [
          [ settings.namespace + '/' + 'article/doi = "10.7554/eLife.000536"',
            {
             settings.namespace + '/' + 'article/doi': {'value': '10.7554/eLife.000536'},
             settings.namespace + '/' + 'article/doi-url': {'value': 'http://dx.doi.org/10.7554/eLife.000536'},
             #settings.namespace + '/' + 'article/pmid': {'value': ''},
             settings.namespace + '/' + 'article/journal-id': {'value': 'eLife'},
             settings.namespace + '/' + 'article/journal-title': {'value': 'eLife'},
             #settings.namespace + '/' + 'article/journal-issn-ppub': {'value': ''},
             settings.namespace + '/' + 'article/journal-issn-epub': {'value': '2050-084X'},
             settings.namespace + '/' + 'article/publisher': {'value': 'eLife Sciences Publications, Ltd'},
             settings.namespace + '/' + 'article/article-title': {'value': 'Prophylactic Platelets in Dengue: Survey Responses Highlight Lack of an Evidence Base'},
             settings.namespace + '/' + 'article/abstract': {'value': '<title>Textbook Summary</title><p>A low platelet count is a common feature of dengue infection. It is thought that the platelet count correlates with the severity of the infection and may contribute to the risk of developing haemorrhage, a well-recognised complication of dengue. As a result of this platelet transfusions are used in some settings to reduce the risk of haemorrhage. There is currently no evidence to support this practice, and platelet transfusions are costly and sometimes harmful. We conducted a survey assessing the use of platelets in dengue. Respondents were all physicians involved with the treatment of patients with dengue. Respondents were asked that their answers reflected what they would do if they were the treating physician. We received 306 responses from 20 different countries. The striking feature of the survey responses was the heterogeneity of approaches to the use of platelets in dengue. These findings highlight the variation in clinical practice and lack of an evidence base in this area and underscore the importance of conducting prospective clinical trials to address this key question in dengue clinical management.</p>'},
             settings.namespace + '/' + 'article/article-type': {'value': 'Research'},
             settings.namespace + '/' + 'article/article-institution': {'value': 'Pediatric Dengue Vaccine Initiative'},
             settings.namespace + '/' + 'article/article-country': {'value': 'United States of America'},
             settings.namespace + '/' + 'article/subject-area': {'value': 'Microbiology and infectious disease'},
             settings.namespace + '/' + 'article/research-organism': {'value': 'None'},
             settings.namespace + '/' + 'article/author': {'value': ['James Whitehorn','James Whitehorn','Rosmari Rodriguez Roche','Maria G. Guzman','Eric Martinez','Wilmar Villamil Gomez','Leonard Nainggolan','Ida Safitri Laksono','Ajay Mishra','Lucy Lum','Abul Faiz','Amadou Sall','Joshua Dawurung','Alvaro Borges','Alvaro Borges','Yee-Sin Leo','Lucille Blumberg','Daniel G. Bausch','Axel Kroeger','Olaf Horstick','Guy Thwaites','Heiman Wertheim','Mattias Larsson','Tran Tinh Hien','Rosanna Peeling','Bridget Wills','Cameron Simmons','Jeremy Farrar']},
             settings.namespace + '/' + 'article/author-surname': {'value': ['Whitehorn','Whitehorn','Roche','Guzman','Martinez','Villamil Gomez','Nainggolan','Laksono','Mishra','Lum','Faiz','Sall','Dawurung','Borges','Borges','Leo','Blumberg','Bausch','Kroeger','Horstick','Thwaites','Wertheim','Larsson','Hien','Peeling','Wills','Simmons','Farrar']},
             settings.namespace + '/' + 'article/author-given-names': {'value': ['James','James','Rosmari Rodriguez','Maria G.','Eric','Wilmar','Leonard','Ida Safitri','Ajay','Lucy','Abul','Amadou','Joshua','Alvaro','Alvaro','Yee-Sin','Lucille','Daniel G.','Axel','Olaf','Guy','Heiman','Mattias','Tran Tinh','Rosanna','Bridget','Cameron','Jeremy']},
             settings.namespace + '/' + 'article/author-department': {'value': ['Department of Clinical Research', 'Oxford University Clinical Research Unit', '', '', '', '', '', 'Paediatric Department', '', 'Department of Paediatrics', '', '', '', 'Copenhagen HIV Programme', '', 'Department of Infectious Diseases', '', '', 'Special Programme for Research and Training in Tropical Diseases', '', 'Department of Infectious Disease/Centre for Clinical Infection and Diagnostics Research', 'Oxford University Clinical Research Unit', 'Oxford University Clinical Research Unit', 'Oxford University Clinical Research Unit', 'Department of Clinical Research', 'Oxford University Clinical Research Unit', 'Oxford University Clinical Research Unit', 'Oxford University Clinical Research Unit']},
             settings.namespace + '/' + 'article/author-institution': {'value': ['London School of Hygiene and Tropical Medicine', 'Hospital for Tropical Diseases', 'Instituto de Medicina Tropical Pedro Kouri', 'Instituto de Medicina Tropical Pedro Kouri', 'Instituto de Medicina Tropical Pedro Kouri', 'Hospital Universitario de Sincelejo', 'University of Indonesia', 'Gadjah Mada University', 'Sunderlal Memorial Hospital', 'University of Malaya', 'Sir Sallimullah Medical College', 'Institute Pasteur', 'University of Maiduguri Teaching Hospital', 'University of Copenhagen', 'University Hospital, Federal University of Minas Gerais', 'Tan Tock Seng Hospital', 'National Institute for Communicable Diseases', 'Tulane School of Public Health and Tropical Medicine', 'World Health Organization', 'Institute of Public Health, University of Heidelberg', 'King\'s College London', 'Hospital for Tropical Diseases', 'Hospital for Tropical Diseases', 'Hospital for Tropical Diseases', 'London School of Hygiene and Tropical Medicine', 'Hospital for Tropical Diseases', 'Hospital for Tropical Diseases', 'Hospital for Tropical Diseases']},
             settings.namespace + '/' + 'article/author-city': {'value': ['London', 'Ho Chi Minh City', 'Havana', 'Havana', 'Havana', 'Sincelejo', 'Jakarta', 'Yogyakarta', 'Delhi', 'Kuala Lumpur', 'Dhaka', 'Dakar', 'Borno State', 'Copenhagen', 'Belo Horizonte', 'Singapore', 'Johannesburg', 'New Orleans, Louisiana', 'Geneva', 'Heidelberg', 'London', 'Ho Chi Minh City', 'Ho Chi Minh City', 'Ho Chi Minh City', 'London', 'Ho Chi Minh City', 'Ho Chi Minh City', 'Ho Chi Minh City']},
             settings.namespace + '/' + 'article/author-country': {'value': ['United Kingdom', 'Vietnam', 'Cuba', 'Cuba', 'Cuba', 'Colombia', 'Indonesia', 'Indonesia', 'India', 'Malaysia', 'Bangladesh', 'Senegal', 'Nigeria', 'Denmark', 'Brazil', 'Singapore', 'South Africa', 'United States of America', 'Switzerland', 'Germany', 'United Kingdom', 'Vietnam', 'Vietnam', 'Vietnam', 'United Kingdom', 'Vietnam', 'Vietnam', 'Vietnam']},
             settings.namespace + '/' + 'article/author-corresponding': {'value': ['James Whitehorn', 'James Whitehorn']},
             settings.namespace + '/' + 'article/author-corresponding-surname': {'value': ['Whitehorn', 'Whitehorn']},
             settings.namespace + '/' + 'article/author-corresponding-given-names': {'value': ['James', 'James']},
             settings.namespace + '/' + 'article/author-corresponding-department': {'value': ['Department of Clinical Research', 'Oxford University Clinical Research Unit']},
             settings.namespace + '/' + 'article/author-corresponding-institution': {'value': ['London School of Hygiene and Tropical Medicine', 'Hospital for Tropical Diseases']},
             settings.namespace + '/' + 'article/author-corresponding-city': {'value': ['London', 'Ho Chi Minh City']},
             settings.namespace + '/' + 'article/author-corresponding-country': {'value': ['United Kingdom', 'Vietnam']},
             settings.namespace + '/' + 'article/correspondence': {'value': '<label>&#x002A;</label>For correspondence: <email>james.whitehorn@lshtm.ac.uk</email> (JW)'},
             settings.namespace + '/' + 'article/author-notes': {'value': """<label>Author Contributions</label>
		<p>Conception and design: JW, BW, JF, TTH</p>
		<p>Acquisition of data: JW, BW, JF, TTH</p>
		<p>Analysis and interpretation of data: JW, BW, JF, TTH</p>
		<p>Drafting or revising the article: JW, BW, JF, TTH</p>
		<p>Contributed unpublished essential data or reagents: JW, BW, JF, TTH</p>
		<p>Drafting or revising the article: JW, BW, JF, TTH</p>
		<p>INSERT TEXT FROM FREEFORM BOX: AUTHOR INITIALS</p>"""},
             settings.namespace + '/' + 'article/keyword': {'value': ['platelets','dengue','thrombocytopenia']},
             settings.namespace + '/' + 'article/pub-date-date': {'value': 'June 26, 2012'},
             settings.namespace + '/' + 'article/pub-date-day': {'value': '26'},
             settings.namespace + '/' + 'article/pub-date-month': {'value': '6'},
             settings.namespace + '/' + 'article/pub-date-year': {'value': '2012'},
             settings.namespace + '/' + 'article/pub-date-timestamp': {'value': '1340668800'},
             settings.namespace + '/' + 'article/received-date-date': {'value': 'March 30, 2012'},
             settings.namespace + '/' + 'article/received-date-day': {'value': '30'},
             settings.namespace + '/' + 'article/received-date-month': {'value': '3'},
             settings.namespace + '/' + 'article/received-date-year': {'value': '2012'},
             settings.namespace + '/' + 'article/received-date-timestamp': {'value': '1333065600'},
             settings.namespace + '/' + 'article/accepted-date-date': {'value': 'May 17, 2012'},
             settings.namespace + '/' + 'article/accepted-date-day': {'value': '17'},
             settings.namespace + '/' + 'article/accepted-date-month': {'value': '5'},
             settings.namespace + '/' + 'article/accepted-date-year': {'value': '2012'},
             settings.namespace + '/' + 'article/accepted-date-timestamp': {'value': '1337212800'},
             settings.namespace + '/' + 'article/award-group-funding-source': {'value': 'National Institutes of Health'},
             settings.namespace + '/' + 'article/award-group-award-id': {'value': 'GM18458'},
             settings.namespace + '/' + 'article/award-group-principle-award-recipient': {'value': 'Author name(s)'},
             settings.namespace + '/' + 'article/funding-statement': {'value': 'The funding sources were not involved in study design; collection, analysis, and interpretation of data; writing the article; and/or the decision to submit to the journal'},
             settings.namespace + '/' + 'article/copyright-statement': {'value': 'Copyright &#x00A9; 2012, Whitehorn et al.'},
             settings.namespace + '/' + 'article/copyright-year': {'value': '2012'},
             settings.namespace + '/' + 'article/copyright-holder': {'value': 'Whitehorn et al.'},
             settings.namespace + '/' + 'article/license': {'value': ' This work is licensed under a Creative Commons Attribution 3.0 Unported License. This is an open-access article distributed under the terms of the Creative Commons Attribution License, which permits unrestricted use, distribution, and reproduction in any medium, provided the original author and source are credited.'},
             settings.namespace + '/' + 'article/license-type': {'value': 'open-access'},
             settings.namespace + '/' + 'article/license-url': {'value': 'http://creativecommons.org/licenses/by/3.0/'},
             settings.namespace + '/' + 'article/ack': {'value': '<p>The authors would like to thank Dr Osvaldo Castro from IPK in Cuba for his assistance in distributing the questionnaires.</p>'},
             settings.namespace + '/' + 'article/conflict': {'value': """<label>Competing interests</label>
	<p>The authors have declared that no competing interests exist.</p>"""},
             settings.namespace + '/' + 'article/ref': {'value': ['Guzman MG, Halstead SB, Artsob H, Buchy P, Farrar J, et al. (2010) Dengue: a continuing global threat. Nat Rev Microbiol 8: S7&#x2013;S16.', 'Lee VJ, Lye DC, Sun Y, Fernandez G, Ong A, et al. (2008) Predictive value of simple clinical and laboratory variables for dengue hemorrhagic fever in adults. J Clin Virol 42: 34&#x2013;39', 'La Russa VF, Innis BL (1995) Mechanisms of dengue virus-induced bone marrow suppression. Baillieres Clin Haematol 8: 249&#x2013;270', 'Lei HY, Yeh TM, Liu HS, Lin YS, Chen SH, et al. (2001) Immunopathogenesis of dengue virus infection. J Biomed Sci 8: 377&#x2013;388', 'Alonzo MT, Lacuesta TL, Dimaano EM, Kurosu T, Suarez LA, et al. (2012) Platelet apoptosis and apoptotic platelet clearance by macrophages in secondary dengue virus infections. J Infect Dis 205: 1321&#x2013;1329', 'Krishnamurti C, Kalayanarooj S, Cutting MA, Peat RA, Rothwell SW, et al. (2001) Mechanisms of hemorrhage in dengue without circulatory collapse. Am J Trop Med Hyg 65: 840&#x2013;847', 'Noisakran S, Chokephaibulkit K, Songprakhon P, Onlamoon N, Hsiao HM, et al. (2009) A re-evaluation of the mechanisms leading to dengue hemorrhagic fever. Ann N Y Acad Sci 1171: E24&#x2013;35', 'WHO (2009) Dengue: guidelines for diagnosis, treatment, prevention and control - New edition. Geneva: World Health Organisation.', 'WHO (2011) Comprehensive guidelines for the prevention and control of dengue and dengue haemorrhagic fever, revised and expanded edition.. In: Asia ROfS-E, editor. Delhi.', 'India Go (2008) Guidelines for clinical management of dengue fever, dengue haemorrhagic fever and dengue shock syndrome. In: Programme DoNVBDC, editor. Delhi.', 'Verdeal J, Filho RC, Vanzillotta C, Macedo G, Bozza F, et al. (2011) Guidelines for the management of patients with severe forms of dengue. Rev Bras Ter Intensiva 23: 125&#x2013;133', 'Lum LC, Abdel-Latif Mel A, Goh AY, Chan PW, Lam SK (2003) Preventive transfusion in Dengue shock syndrome-is it necessary? J Pediatr 143: 682&#x2013;684', 'Lye DC, Lee VJ, Sun Y, Leo YS (2009) Lack of efficacy of prophylactic platelet transfusion for severe thrombocytopenia in adults with acute uncomplicated dengue infection. Clin Infect Dis 48: 1262&#x2013;1265', 'Kurukularatne C, Dimatatac F, Teo DL, Lye DC, Leo YS (2011) When less is more: can we abandon prophylactic platelet transfusion in Dengue fever? Ann Acad Med Singapore 40: 539&#x2013;537', 'Sharma A, Charles K, Chadee D, Teelucksingh S (2012) Dengue hemorrhagic Fever in trinidad and tobago: a case for a conservative approach to platelet transfusion. Am J Trop Med Hyg 86: 531&#x2013;535']},
             settings.namespace + '/' + 'article/ref-publication-type': {'value': ['journal', 'journal', 'journal', 'journal', 'journal', 'journal', 'journal', 'book', 'book', 'other', 'journal', 'journal', 'journal', 'journal', 'journal']},
             settings.namespace + '/' + 'article/ref-article-title': {'value': ['Dengue: a continuing global threat', 'Predictive value of simple clinical and laboratory variables for dengue hemorrhagic fever in adults', 'Mechanisms of dengue virus-induced bone marrow suppression', 'Immunopathogenesis of dengue virus infection', 'Platelet apoptosis and apoptotic platelet clearance by macrophages in secondary dengue virus infections', 'Mechanisms of hemorrhage in dengue without circulatory collapse', 'A re-evaluation of the mechanisms leading to dengue hemorrhagic fever', 'Dengue: guidelines for diagnosis, treatment, prevention and control - New edition', 'Comprehensive guidelines for the prevention and control of dengue and dengue haemorrhagic fever, revised and expanded edition', 'Guidelines for clinical management of dengue fever, dengue haemorrhagic fever and dengue shock syndrome', 'Guidelines for the management of patients with severe forms of dengue', 'Preventive transfusion in Dengue shock syndrome-is it necessary?', 'Lack of efficacy of prophylactic platelet transfusion for severe thrombocytopenia in adults with acute uncomplicated dengue infection', 'When less is more: can we abandon prophylactic platelet transfusion in Dengue fever?', 'Dengue hemorrhagic Fever in trinidad and tobago: a case for a conservative approach to platelet transfusion']},
             settings.namespace + '/' + 'article/ref-authors': {'value': ['Guzman MG, Halstead SB, Artsob H, Buchy P, Farrar J, et al.', 'Lee VJ, Lye DC, Sun Y, Fernandez G, Ong A, et al.', 'La Russa VF, Innis BL', 'Lei HY, Yeh TM, Liu HS, Lin YS, Chen SH, et al.', 'Alonzo MT, Lacuesta TL, Dimaano EM, Kurosu T, Suarez LA, et al.', 'Krishnamurti C, Kalayanarooj S, Cutting MA, Peat RA, Rothwell SW, et al.', 'Noisakran S, Chokephaibulkit K, Songprakhon P, Onlamoon N, Hsiao HM, et al.', '', '', 'India Go', 'Verdeal J, Filho RC, Vanzillotta C, Macedo G, Bozza F, et al.', 'Lum LC, Abdel-Latif Mel A, Goh AY, Chan PW, Lam SK', 'Lye DC, Lee VJ, Sun Y, Leo YS', 'Kurukularatne C, Dimatatac F, Teo DL, Lye DC, Leo YS', 'Sharma A, Charles K, Chadee D, Teelucksingh S']},
             settings.namespace + '/' + 'article/ref-authors-etal': {'value': ['et al.', 'et al.', '', 'et al.', 'et al.', 'et al.', 'et al.', '', '', '', 'et al.', '', '', '', '']},
             settings.namespace + '/' + 'article/ref-year': {'value': ['2010', '2008', '1995', '2001', '2012', '2001', '2009', '2009', '2011', '2008', '2011', '2003', '2009', '2011', '2012']},
             settings.namespace + '/' + 'article/ref-source': {'value': ['Nat Rev Microbiol', 'J Clin Virol', 'Baillieres Clin Haematol', 'J Biomed Sci', 'J Infect Dis', 'Am J Trop Med Hyg', 'Ann N Y Acad Sci', '', '', '', 'Rev Bras Ter Intensiva', 'J Pediatr', 'Clin Infect Dis', 'Ann Acad Med Singapore', 'Am J Trop Med Hyg']},
             settings.namespace + '/' + 'article/ref-volume': {'value': ['8', '42', '8', '8', '205', '65', '1171', '', '', '', '23', '143', '48', '40', '86']},
             settings.namespace + '/' + 'article/ref-fpage': {'value': ['S7', '34', '249', '377', '1321', '840', 'E24', '', '', '', '125', '682', '1262', '539', '531']},
             settings.namespace + '/' + 'article/ref-lpage': {'value': ['S16', '39', '270', '388', '1329', '847', '35', '', '', '', '133', '684', '1265', '537', '535']},
             settings.namespace + '/' + 'article/ref-doi': {'value': ['', '', '', '', '', '', '', '', '', '', '', '', '', '', '']},
             settings.namespace + '/' + 'article/ref-pmid': {'value': ['', '', '', '', '', '', '', '', '', '', '', '', '', '', '']},
             settings.namespace + '/' + 'article/ref-collab': {'value': ['', '', '', '', '', '', '', 'WHO', 'WHO', '', '', '', '', '', '']},
             settings.namespace + '/' + 'article/ref-publisher-loc': {'value': ['', '', '', '', '', '', '', 'Geneva', '', '', '', '', '', '', '']},
             settings.namespace + '/' + 'article/ref-publisher-name': {'value': ['', '', '', '', '', '', '', 'World Health Organisation', '', '', '', '', '', '', '']},
             
             #settings.namespace + '/' + 'article/citation': {'value': ''},
             
             
            }
          ]
        ]
      }
    },
]