import settings

namespaces = [
  {'namespace': 'article'},
  {'namespace': 'person'},
  {'namespace': 'ref'},
  {'namespace': 'alm'},
]

tags = [
  {'tag': 'article/doi',		'desc': ''},
  {'tag': 'article/doi-url',		'desc': ''},
  {'tag': 'article/pmid',		'desc': ''},
  {'tag': 'article/journal-id',		'desc': ''},
  {'tag': 'article/journal-title',		'desc': ''},
  {'tag': 'article/journal-issn-ppub',		'desc': ''},
  {'tag': 'article/journal-issn-epub',		'desc': ''},
  {'tag': 'article/publisher',		'desc': ''},
  {'tag': 'article/article-title',		'desc': ''},
  {'tag': 'article/abstract',		'desc': ''},
  {'tag': 'article/article-type',		'desc': ''},
  {'tag': 'article/article-institution',		'desc': ''},
  {'tag': 'article/article-country',		'desc': ''},
  {'tag': 'article/subject-area',		'desc': ''},
  {'tag': 'article/research-organism',		'desc': ''},
  {'tag': 'article/author',		'desc': ''},
  {'tag': 'article/author-surname',		'desc': ''},
  {'tag': 'article/author-given-names',		'desc': ''},
  {'tag': 'article/author-department',		'desc': ''},
  {'tag': 'article/author-institution',		'desc': ''},
  {'tag': 'article/author-city',		'desc': ''},
  {'tag': 'article/author-country',		'desc': ''},
  {'tag': 'article/author-corresponding',		'desc': ''},
  {'tag': 'article/author-corresponding-surname',		'desc': ''},
  {'tag': 'article/author-corresponding-given-names',		'desc': ''},
  {'tag': 'article/author-corresponding-department',		'desc': ''},
  {'tag': 'article/author-corresponding-institution',		'desc': ''},
  {'tag': 'article/author-corresponding-city',		'desc': ''},
  {'tag': 'article/author-corresponding-country',		'desc': ''},
  {'tag': 'article/correspondence',		'desc': ''},
  {'tag': 'article/author-notes',		'desc': ''},
  {'tag': 'article/keyword',		'desc': ''},
  {'tag': 'article/pub-date-date',		'desc': ''},
  {'tag': 'article/pub-date-day',		'desc': ''},
  {'tag': 'article/pub-date-month',		'desc': ''},
  {'tag': 'article/pub-date-year',		'desc': ''},
  {'tag': 'article/pub-date-timestamp',		'desc': ''},
  {'tag': 'article/received-date-date',		'desc': ''},
  {'tag': 'article/received-date-day',		'desc': ''},
  {'tag': 'article/received-date-month',		'desc': ''},
  {'tag': 'article/received-date-year',		'desc': ''},
  {'tag': 'article/received-date-timestamp',		'desc': ''},
  {'tag': 'article/accepted-date-date',		'desc': ''},
  {'tag': 'article/accepted-date-day',		'desc': ''},
  {'tag': 'article/accepted-date-month',		'desc': ''},
  {'tag': 'article/accepted-date-year',		'desc': ''},
  {'tag': 'article/accepted-date-timestamp',		'desc': ''},
  {'tag': 'article/award-group-funding-source',		'desc': ''},
  {'tag': 'article/award-group-award-id',		'desc': ''},
  {'tag': 'article/award-group-principle-award-recipient',		'desc': ''},
  {'tag': 'article/funding-statement',		'desc': ''},
  {'tag': 'article/copyright-statement',		'desc': ''},
  {'tag': 'article/copyright-year',		'desc': ''},
  {'tag': 'article/copyright-holder',		'desc': ''},
  {'tag': 'article/license',		'desc': ''},
  {'tag': 'article/license-type',		'desc': ''},
  {'tag': 'article/license-url',		'desc': ''},
  {'tag': 'article/ack',		'desc': ''},
  {'tag': 'article/conflict',		'desc': ''},
  {'tag': 'article/ref',		'desc': ''},
  {'tag': 'article/ref-publication-type',		'desc': ''},
  {'tag': 'article/ref-article-title',		'desc': ''},
  {'tag': 'article/ref-authors',		'desc': ''},
  {'tag': 'article/ref-year',		'desc': ''},
  {'tag': 'article/ref-source',		'desc': ''},
  {'tag': 'article/ref-volume',		'desc': ''},
  {'tag': 'article/ref-fpage',		'desc': ''},
  {'tag': 'article/ref-lpage',		'desc': ''},
  {'tag': 'article/ref-doi',		'desc': ''},
  {'tag': 'article/ref-pmid',		'desc': ''},
  {'tag': 'article/ref-collab',		'desc': ''},
  {'tag': 'article/citation',		'desc': ''},
  
  {'tag': 'person/surname',		'desc': ''},
  
  {'tag': 'ref/article-title',		'desc': ''},
  {'tag': 'ref/publication-type',		'desc': ''},
  {'tag': 'ref/doi',		'desc': ''},
  {'tag': 'ref/pmid',		'desc': ''},
  {'tag': 'ref/author',		'desc': ''},
  {'tag': 'ref/year',		'desc': ''},
  {'tag': 'ref/source',		'desc': ''},
  {'tag': 'ref/volume',		'desc': ''},
  {'tag': 'ref/fpage',		'desc': ''},
  {'tag': 'ref/lpage',		'desc': ''},

  {'tag': 'alm/doi',		'desc': ''},
  {'tag': 'alm/source',		'desc': ''},
  {'tag': 'alm/value',		'desc': ''},
  {'tag': 'alm/timespan',		'desc': ''},
  {'tag': 'alm/date-date',		'desc': ''},
  {'tag': 'alm/date-day',		'desc': ''},
  {'tag': 'alm/date-month',		'desc': ''},
  {'tag': 'alm/date-year',		'desc': ''},
  {'tag': 'alm/date-timestamp',		'desc': ''},
  
]

objects = [
    {'obj': 'df97444e-9579-49f1-8302-2dce51c0bd95', 'doi': '10.7554/eLife.000536', 'query':
      {'queries':
        [
          [ settings.namespace + '/' + 'article/doi = "10.7554/eLife.000536"',
            {
             settings.namespace + '/' + 'article/doi': {'value': '10.7554/eLife.000536'},
             settings.namespace + '/' + 'article/doi-url': {'value': 'http://dx.doi.org/10.7554/eLife.000536'},
             #settings.namespace + '/' + 'article/pmid': {'value': ''},
             settings.namespace + '/' + 'article/journal-id': {'value': 'eLife'},
             settings.namespace + '/' + 'article/journal-title': {'value': 'eLife'},
             #settings.namespace + '/' + 'article/journal-issn-ppub': {'value': ''},
             settings.namespace + '/' + 'article/journal-issn-epub': {'value': '2050-084X'},
             settings.namespace + '/' + 'article/publisher': {'value': 'eLife Sciences Publications, Ltd'},
             settings.namespace + '/' + 'article/article-title': {'value': 'Prophylactic Platelets in Dengue: Survey Responses Highlight Lack of an Evidence Base'},
             settings.namespace + '/' + 'article/abstract': {'value': '<title>Textbook Summary</title><p>A low platelet count is a common feature of dengue infection. It is thought that the platelet count correlates with the severity of the infection and may contribute to the risk of developing haemorrhage, a well-recognised complication of dengue. As a result of this platelet transfusions are used in some settings to reduce the risk of haemorrhage. There is currently no evidence to support this practice, and platelet transfusions are costly and sometimes harmful. We conducted a survey assessing the use of platelets in dengue. Respondents were all physicians involved with the treatment of patients with dengue. Respondents were asked that their answers reflected what they would do if they were the treating physician. We received 306 responses from 20 different countries. The striking feature of the survey responses was the heterogeneity of approaches to the use of platelets in dengue. These findings highlight the variation in clinical practice and lack of an evidence base in this area and underscore the importance of conducting prospective clinical trials to address this key question in dengue clinical management.</p>'},
             settings.namespace + '/' + 'article/article-type': {'value': 'Research'},
             settings.namespace + '/' + 'article/article-institution': {'value': 'Pediatric Dengue Vaccine Initiative'},
             settings.namespace + '/' + 'article/article-country': {'value': 'United States of America'},
             settings.namespace + '/' + 'article/subject-area': {'value': 'Microbiology and infectious disease'},
             settings.namespace + '/' + 'article/research-organism': {'value': 'None'},
             settings.namespace + '/' + 'article/author': {'value': ['James Whitehorn','James Whitehorn','Rosmari Rodriguez Roche','Maria G. Guzman','Eric Martinez','Wilmar Villamil Gomez','Leonard Nainggolan','Ida Safitri Laksono','Ajay Mishra','Lucy Lum','Abul Faiz','Amadou Sall','Joshua Dawurung','Alvaro Borges','Alvaro Borges','Yee-Sin Leo','Lucille Blumberg','Daniel G. Bausch','Axel Kroeger','Olaf Horstick','Guy Thwaites','Heiman Wertheim','Mattias Larsson','Tran Tinh Hien','Rosanna Peeling','Bridget Wills','Cameron Simmons','Jeremy Farrar']},
             settings.namespace + '/' + 'article/author-surname': {'value': ['Whitehorn','Whitehorn','Roche','Guzman','Martinez','Villamil Gomez','Nainggolan','Laksono','Mishra','Lum','Faiz','Sall','Dawurung','Borges','Borges','Leo','Blumberg','Bausch','Kroeger','Horstick','Thwaites','Wertheim','Larsson','Hien','Peeling','Wills','Simmons','Farrar']},
             settings.namespace + '/' + 'article/author-given-names': {'value': ['James','James','Rosmari Rodriguez','Maria G.','Eric','Wilmar','Leonard','Ida Safitri','Ajay','Lucy','Abul','Amadou','Joshua','Alvaro','Alvaro','Yee-Sin','Lucille','Daniel G.','Axel','Olaf','Guy','Heiman','Mattias','Tran Tinh','Rosanna','Bridget','Cameron','Jeremy']},
             settings.namespace + '/' + 'article/author-department': {'value': ['Department of Clinical Research', 'Oxford University Clinical Research Unit', '', '', '', '', '', 'Paediatric Department', '', 'Department of Paediatrics', '', '', '', 'Copenhagen HIV Programme', '', 'Department of Infectious Diseases', '', '', 'Special Programme for Research and Training in Tropical Diseases', '', 'Department of Infectious Disease/Centre for Clinical Infection and Diagnostics Research', 'Oxford University Clinical Research Unit', 'Oxford University Clinical Research Unit', 'Oxford University Clinical Research Unit', 'Department of Clinical Research', 'Oxford University Clinical Research Unit', 'Oxford University Clinical Research Unit', 'Oxford University Clinical Research Unit']},
             settings.namespace + '/' + 'article/author-institution': {'value': ['London School of Hygiene and Tropical Medicine', 'Hospital for Tropical Diseases', 'Instituto de Medicina Tropical Pedro Kouri', 'Instituto de Medicina Tropical Pedro Kouri', 'Instituto de Medicina Tropical Pedro Kouri', 'Hospital Universitario de Sincelejo', 'University of Indonesia', 'Gadjah Mada University', 'Sunderlal Memorial Hospital', 'University of Malaya', 'Sir Sallimullah Medical College', 'Institute Pasteur', 'University of Maiduguri Teaching Hospital', 'University of Copenhagen', 'University Hospital, Federal University of Minas Gerais', 'Tan Tock Seng Hospital', 'National Institute for Communicable Diseases', 'Tulane School of Public Health and Tropical Medicine', 'World Health Organization', 'Institute of Public Health, University of Heidelberg', 'King\'s College London', 'Hospital for Tropical Diseases', 'Hospital for Tropical Diseases', 'Hospital for Tropical Diseases', 'London School of Hygiene and Tropical Medicine', 'Hospital for Tropical Diseases', 'Hospital for Tropical Diseases', 'Hospital for Tropical Diseases']},
             settings.namespace + '/' + 'article/author-city': {'value': ['London', 'Ho Chi Minh City', 'Havana', 'Havana', 'Havana', 'Sincelejo', 'Jakarta', 'Yogyakarta', 'Delhi', 'Kuala Lumpur', 'Dhaka', 'Dakar', 'Borno State', 'Copenhagen', 'Belo Horizonte', 'Singapore', 'Johannesburg', 'New Orleans, Louisiana', 'Geneva', 'Heidelberg', 'London', 'Ho Chi Minh City', 'Ho Chi Minh City', 'Ho Chi Minh City', 'London', 'Ho Chi Minh City', 'Ho Chi Minh City', 'Ho Chi Minh City']},
             settings.namespace + '/' + 'article/author-country': {'value': ['United Kingdom', 'Vietnam', 'Cuba', 'Cuba', 'Cuba', 'Colombia', 'Indonesia', 'Indonesia', 'India', 'Malaysia', 'Bangladesh', 'Senegal', 'Nigeria', 'Denmark', 'Brazil', 'Singapore', 'South Africa', 'United States of America', 'Switzerland', 'Germany', 'United Kingdom', 'Vietnam', 'Vietnam', 'Vietnam', 'United Kingdom', 'Vietnam', 'Vietnam', 'Vietnam']},
             settings.namespace + '/' + 'article/author-corresponding': {'value': ['James Whitehorn', 'James Whitehorn']},
             settings.namespace + '/' + 'article/author-corresponding-surname': {'value': ['Whitehorn', 'Whitehorn']},
             settings.namespace + '/' + 'article/author-corresponding-given-names': {'value': ['James', 'James']},
             settings.namespace + '/' + 'article/author-corresponding-department': {'value': ['Department of Clinical Research', 'Oxford University Clinical Research Unit']},
             settings.namespace + '/' + 'article/author-corresponding-institution': {'value': ['London School of Hygiene and Tropical Medicine', 'Hospital for Tropical Diseases']},
             settings.namespace + '/' + 'article/author-corresponding-city': {'value': ['London', 'Ho Chi Minh City']},
             settings.namespace + '/' + 'article/author-corresponding-country': {'value': ['United Kingdom', 'Vietnam']},
             settings.namespace + '/' + 'article/correspondence': {'value': '<label>&#x002A;</label>For correspondence: <email>james.whitehorn@lshtm.ac.uk</email> (JW)'},
             settings.namespace + '/' + 'article/author-notes': {'value': """<label>Author Contributions</label>
		<p>Conception and design: JW, BW, JF, TTH</p>
		<p>Acquisition of data: JW, BW, JF, TTH</p>
		<p>Analysis and interpretation of data: JW, BW, JF, TTH</p>
		<p>Drafting or revising the article: JW, BW, JF, TTH</p>
		<p>Contributed unpublished essential data or reagents: JW, BW, JF, TTH</p>
		<p>Drafting or revising the article: JW, BW, JF, TTH</p>
		<p>INSERT TEXT FROM FREEFORM BOX: AUTHOR INITIALS</p>"""},
             settings.namespace + '/' + 'article/keyword': {'value': ['platelets','dengue','thrombocytopenia']},
             settings.namespace + '/' + 'article/pub-date-date': {'value': 'June 26, 2012'},
             settings.namespace + '/' + 'article/pub-date-day': {'value': '26'},
             settings.namespace + '/' + 'article/pub-date-month': {'value': '6'},
             settings.namespace + '/' + 'article/pub-date-year': {'value': '2012'},
             settings.namespace + '/' + 'article/pub-date-timestamp': {'value': '1340668800'},
             settings.namespace + '/' + 'article/received-date-date': {'value': 'March 30, 2012'},
             settings.namespace + '/' + 'article/received-date-day': {'value': '30'},
             settings.namespace + '/' + 'article/received-date-month': {'value': '3'},
             settings.namespace + '/' + 'article/received-date-year': {'value': '2012'},
             settings.namespace + '/' + 'article/received-date-timestamp': {'value': '1333065600'},
             settings.namespace + '/' + 'article/accepted-date-date': {'value': 'May 17, 2012'},
             settings.namespace + '/' + 'article/accepted-date-day': {'value': '17'},
             settings.namespace + '/' + 'article/accepted-date-month': {'value': '5'},
             settings.namespace + '/' + 'article/accepted-date-year': {'value': '2012'},
             settings.namespace + '/' + 'article/accepted-date-timestamp': {'value': '1337212800'},
              
              
              
            }
          ]
        ]
      }
    },
]